---
- name: Add ppa ppa:remmina-ppa-team/remmina-next
  apt_repository:
    repo: ppa:remmina-ppa-team/remmina-next
    state: present

- name: Install Remmina packages
  apt:
    name: "{{ boxes_remotedesktop_package_name }}"
    state: present
  loop_control:
    loop_var: boxes_remotedesktop_package_name
  loop:
    - remmina
    - remmina-plugin-rdp
    - remmina-plugin-secret
    - remmina-plugin-spice
